// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKIIX6t7dre2e_n3B1E7YAsSKlkGzqHiw',
    appId: '1:25596024554:web:d4062f7228fb8032432993',
    messagingSenderId: '25596024554',
    projectId: 'articulate-aac-2022',
    authDomain: 'articulate-aac-2022.firebaseapp.com',
    storageBucket: 'articulate-aac-2022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4FHRnVg6Bz8ZhYqtIiflpKJ7MpYENaUw',
    appId: '1:25596024554:android:38d55fad1a8397fe432993',
    messagingSenderId: '25596024554',
    projectId: 'articulate-aac-2022',
    storageBucket: 'articulate-aac-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXqVbpP7rDDcc050INwl_U6dq1D4_v_Uk',
    appId: '1:25596024554:ios:523cce812181ac3f432993',
    messagingSenderId: '25596024554',
    projectId: 'articulate-aac-2022',
    storageBucket: 'articulate-aac-2022.appspot.com',
    iosClientId:
        '25596024554-8votmhjs2gf5rph7ri1su7jbo7t6qsbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.articulate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXqVbpP7rDDcc050INwl_U6dq1D4_v_Uk',
    appId: '1:25596024554:ios:523cce812181ac3f432993',
    messagingSenderId: '25596024554',
    projectId: 'articulate-aac-2022',
    storageBucket: 'articulate-aac-2022.appspot.com',
    iosClientId:
        '25596024554-8votmhjs2gf5rph7ri1su7jbo7t6qsbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.articulate',
  );
}
