name: articulate
description: Articulate is an augmentative and alternative communication (AAC) mobile application for children with Autism spectrum disorder (ASD). This app is developed by Afiqah Ahmad SUDK1802300, under SEGi University Kota Damansara, in accordance to completing the mandatory Final Year Project course. For any questions, please email to afiqahahmadasraf@gmail.com.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  cloud_firestore: ^3.4.0
  google_fonts: ^3.0.1
  firebase_storage: ^10.3.4
  firebase_auth: ^3.6.2
  google_sign_in: ^5.4.0 #remove
  firebase_core_platform_interface: 4.5.1
  image_picker: ^0.8.6
  flutter_tts: ^3.6.0
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^10.2.1
  fluttertoast: ^8.1.1
  speech_to_text: ^6.1.0
  email_validator: ^2.1.17
  audioplayers: ^0.20.1
  reorderable_grid_view: ^2.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0

  flutter_native_splash: ^2.2.14
flutter_native_splash:
  color: "#AFE1FF"
  image: assets/img/splash_screen.png

  flutter_launcher_icons: "^0.10.0"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/splash_screen.png"

  

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/tiles/
    - assets/img/
    - assets/game/
    - assets/manual/
    - assets/
